name=Adafruit TCS34725 Soft i2c
version=2.0.0
author=CR24
maintainer=CR24
sentence=Driver for Adafruit's TCS34725 RGB Color Sensor Breakout with software i2c
paragraph=Driver for Adafruit's TCS34725 RGB Color Sensor Breakout with software i2c
category=Sensors
url=https://github.com/ItsCR24/Adafruit_TCS34725_SoftI2C
architectures=*
