name=Adafruit TCS34725 Soft I2C
version=2.0.1
author=CR24
maintainer=CR24
sentence=Driver for Adafruit's TCS34725 RGB Color Sensor Breakout with software I2C
paragraph=Driver for Adafruit's TCS34725 RGB Color Sensor Breakout with software I2C
category=Sensors
url=https://github.com/ItsCR24/Adafruit_TCS34725_SoftI2C
architectures=*
